import { Box, Button, Container, Flex, HStack, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { MenuItem } from '../components/molecules/MenuItem/MenuItem'
import styles from '../styles/Home.module.css'
import { Hero } from '../components/molecules/Hero/Hero'
import { TopBar } from '../components/organisms/TopBar/TopBar'
import { LandingBody } from '../components/organisms/LandingBody/LandingBody'
import { LandingFooter } from '../components/organisms/LandingFooter/LandingFooter'
import { useSession } from 'next-auth/react'

const Home: NextPage = () => {
  	return (
    <div className={styles.container}>
      	<Head>
      	  <title>Kodix</title>
      	  <meta name="description" content="Generated by create next app" />
      	  <link rel="icon" href="/favicon.ico" />
      	</Head>


      	<TopBar index={-1}/>

      	<Flex>
      	  <Hero />
      	</Flex>

      	<LandingBody />
      	<LandingFooter></LandingFooter>
    </div>
  )
}

export default Home
